# Generated by Django 3.0.4 on 2020-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pcid', models.CharField(max_length=10, unique=True)),
                ('order', models.CharField(max_length=10, unique=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('all_mac', models.CharField(max_length=200)),
                ('ipmi_mac', models.CharField(blank=True, max_length=45, null=True)),
                ('workstation', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'unit_info',
                'managed': False,
            },
        ),
    ]
